apiVersion: app/v1
kind: Deployment
metadata:
  name: survy-app-deploy
  namespace: python-app
  labels:
    app: survey-app

spec:
  selector:
    matchLables:
  replicas: 2
  template:
    metadata:
      labels:
        app: survey-app
   
    
    spec:
      containers:
      - name: survey-app
        image: fadydevops/survey-img
        port:
        - contanierport: 8000
        